[Copyright]
hash = "sha1-ed6768b21eb5e05d75dd18c9cb9ed38e56de94d6"
other = "&copy; 2020 <a href='https://github.com/prologic' target='_blank'>James Mills</a>. 版权所有."

[CopyrightCreator]
hash = "sha1-e7946380febed70ea56d525f57b79799b220e087"
other = "由 <a href='https://github.com/prologic' target='_blank'>James Mills</a> 创建"

[ForgottenPasswordContent]
hash = "sha1-122216d4af117201b618588c4a2969c8ee9a1c16"
other = "如果您忘记了密码, 只要您记住注册时使用的用户名和电子邮件地址并保留对电子邮件的访问权限，就可以请求<a href=\"/resetPassword\">重置密码</a>(<i>我们 <b>从不</b> 存储您的邮件地址!</i>)."

[Instead]
hash = "sha1-6568964b0e39083c6acb94093d9e6cd117dbe508"
other = "."

[LoginFormLogin]
hash = "sha1-4e5a2893bdcc7d239c1db72e4c4ffbe4bea73174"
other = "登录"

[LoginFormPassword]
hash = "sha1-8be3c943b1609fffbfc51aad666d0a04adf83c9d"
other = "密码"

[LoginFormRemberMe]
hash = "sha1-06716884880fe454166b2b598e01544d1aefd999"
other = "记住我?"

[LoginFormUsername]
hash = "sha1-84c29015de33e5d22422382a372caba5c58f8c01"
other = "用户名"

[LoginHowToContent]
hash = "sha1-9afcf1df91de941735d380b6b91b01a0de6e771b"
other = "      <p>\n填写在创建账号时使用的用户名和密码，登录{{.InstanceName}}.\n </p><p>\n 如果您不想每隔几个小时登录一次，请选中“记住我”复选框.</p><p>\n还没有账号?\n您可以点击<a href=\"/register\">注册</a>马上创建一个.</p>\n"

[LoginHowToTitle]
hash = "sha1-097f2ed883de33056433137a3d1ddc53da9931df"
other = "如何登录"

[LoginNoAccountSummary]
hash = "sha1-f838dc11db151df79ee689f598453d38bbac6fe9"
other = "还没有账号"

[LoginNoAccountTitle]
hash = "sha1-f838dc11db151df79ee689f598453d38bbac6fe9"
other = "还没有账号"

[LoginSummary]
hash = "sha1-bab7c351f3af43d5f4c56baf11d65b4384a1ba86"
other = "在 {{ .InstanceName }} 登录你的社交账号"

[LoginTitle]
hash = "sha1-ada2e9e96fa9ce85430225b412068b5b62b79800"
other = "登录"

[MenuAbout]
hash = "sha1-6b21fb791ac05170893860c248401cd24a59b732"
other = "关于我们"

[MenuAbuse]
hash = "sha1-411d6ee2454b2cd4eada9d338861ed000fc07b6e"
other = "举报"

[MenuAtom]
hash = "sha1-41dded417052424bdcf3c39f6c8664147fae6806"
other = "Atom"

[MenuHelp]
hash = "sha1-c47ae15370cfe1ed2781eedc1dc2547d12d9e972"
other = "帮助"

[MenuPrivacy]
hash = "sha1-cf01481f626d5127ec7732fcbdb29504f08abefd"
other = "隐私"

[MenuSupport]
hash = "sha1-f32d5a3b17e614297417cc279a7ec1cd02274d65"
other = "支持"

[NavDiscover]
hash = "sha1-4827ea22716a74aaf8bbe499fc314bb93f73c65e"
other = "发现"

[NavFeeds]
hash = "sha1-ffe8e99492ee9b850395d53f6c519938952fde0d"
other = "订阅"

[NavFollow]
hash = "sha1-66587a7a62a90fc91c4c88f1872bedaa52d23a35"
other = "关注"

[NavLogin]
hash = "sha1-4e5a2893bdcc7d239c1db72e4c4ffbe4bea73174"
other = "登录"

[NavLogout]
hash = "sha1-e43d612e11f1568f2373e719d4c4b08dcecdc7cc"
other = "退出"

[NavMentions]
hash = "sha1-85e12bc6f2e56024e47cc826a14968247a52dc54"
other = "提及"

[NavMessages]
hash = "sha1-f1702b4686278becffc88baabe6f4b7a8355532c"
other = "消息"

[NavRegister]
hash = "sha1-d672995a14650d0e018026b64f297663d8c71c8d"
other = "注册"

[NavSettings]
hash = "sha1-c7f73bb54d928922c3838bb789ee9fb8a5b1eb37"
other = "设置"

[NavTimeline]
hash = "sha1-018514a3d58aa08353dd5e387ee29de45981c409"
other = "动态"

[RegisterDisabledMessage]
hash = "sha1-14d26e1e7754b30ed7402bbaf188baa629d8a79b"
other = "当前实例禁止注册, 请联系管理员"

[RegisterFormEmail]
hash = "sha1-c94d3175a6560565410511df2cebab9cda96027e"
other = "电子邮件"

[RegisterFormEmailSummary]
hash = "sha1-a002997d17e931c8aa6c7b45ff19550706a116b5"
other = "注意：我们实际上并不存储此信息！如果您忘记或丢失电子邮件帐户信息，我们将无法恢复您的帐户！"

[RegisterFormLogin]
hash = "sha1-8cc61755932c795b961af3625f92b8a3a9d7e5c3"
other = "已有账号? <a href='/login'>/登录</a> "

[RegisterFormPassword]
hash = "sha1-8be3c943b1609fffbfc51aad666d0a04adf83c9d"
other = "密码"

[RegisterFormRegister]
hash = "sha1-d672995a14650d0e018026b64f297663d8c71c8d"
other = "注册"

[RegisterFormUsername]
hash = "sha1-84c29015de33e5d22422382a372caba5c58f8c01"
other = "用户名"

[RegisterGuidelines]
hash = "sha1-09f2d7efb99d67b64c2193d184c5bc760bc8c412"
other = "我同意遵守 <a href='/abuse'>社区准则</a>."

[RegisterHowToContent]
hash = "sha1-0d58603b0b6a7a7d38c0ea9d73a9c54f68f76535"
other = "<p>\n你将在{{ .InstanceName }}创建一个新的<a href='https://twt.social' target='_blank'>Twt.social</a>\n\n</p>\n<p>\n在 {{ .InstanceName }} 注册一个账号, 遵守<a href='/abuse'>政策</a>中的社区准则.\n</p>\n<p>\n<ul>\n<li>选择一个用户名</li>\n<li>创建一个安全的密码</li>\n<li>提供电子邮件用于找回您的密码</li>\n</ul>\n</p>\n<p>\n选择任何你喜欢的用户 (<i>只要在 {{ .InstanceName }}可用</i>).\n</p>\n<p>\n请注意: 我们 <b>不储存</b> 电子邮件地址, 请记住您的电子邮件地址,  如果电子邮件地址丢失或忘记, 我们将不能恢复您的账号或帮您找回密码\n</p>"

[RegisterHowToTitle]
hash = "sha1-61b07a27c8f9b25d9065b26390b2884fb025586e"
other = "如何创建账号"

[RegisterLinkTitle]
hash = "sha1-5b402e3dfa8bfeaa6620b1ee5bf38fb965bcbe3c"
other = "注册"

[RegisterSummary]
hash = "sha1-87d65ce0904f254e39fbb671ccd7a58f79cfa18b"
other = "在{{.InstanceName}}上创建并注册一个新的社交帐户"

[RegisterTitle]
hash = "sha1-0b81497c8589af2714a1ddbeb62b3a4be679c318"
other = "注册"

[ResetPasswordFormEmail]
hash = "sha1-c94d3175a6560565410511df2cebab9cda96027e"
other = "电子邮件"

[ResetPasswordFormReset]
hash = "sha1-3fb75e3bfe4de94eb5198656fa9de95352dab915"
other = "重置密码"

[ResetPasswordFormUsername]
hash = "sha1-84c29015de33e5d22422382a372caba5c58f8c01"
other = "用户名"

[ResetPasswordHowToContent]
hash = "sha1-76cf47fef180d4e68557d75ef348e2569c5d4b7d"
other = " \n<p>\n使用左侧的表格来恢复您的帐户并重置密码。\n只需填写用于创建帐户的用户名和电子邮件地址即可。</p>\n<p>\n但是请注意，您必须在此处提供与最初创建帐户时相同的电子邮件地址。我们<b>不会</b>实际存储档案中的电子邮件地址，所以如果你没有访问或已经忘记了自己的电子邮件地址，那么你将无法恢复您的帐户。\n</p>"

[ResetPasswordHowToTitle]
hash = "sha1-8b19f439204c9f765b9d0ddc81459d9dff6e5a1b"
other = "如何重置您的密码"

[ResetPasswordLinkTitle]
hash = "sha1-19dda05128bca657bda59fd4ada178cc349f00ec"
other = "忘记密码"

[ResetPasswordSummary]
hash = "sha1-f4c4fc1a4556f29189ff762b92fc4107b48f900f"
other = "填写下面表单重置您的密码"

[ResetPasswordTitle]
hash = "sha1-3fb75e3bfe4de94eb5198656fa9de95352dab915"
other = "重置密码"
